name: Deploy to Amazon

on:
  push:
    branches: [ master ]

env:
  AWS_REGION: eu-north-1 # set this to your preferred AWS region, e.g. us-west-1

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: eu-north-1
        role-to-assume: arn:aws:iam::968382676337:role/github-actions-s3-deploy
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Build
      run:  |
        npm ci
        npm run build
    
    - name: Deploy
      run: |
        aws s3 sync ./build/client s3://website-stack-s3bucketcontent4a570435-xethiwm0rlzo --recursive
